### ISSUE TITLE
Aliases - todo

### ISSUE THREAD

**Issue by jtokarchuk** [Nextitude/nxs#1]
- [ ] nxs-list (on it's own, lists repositories)
- [ ] nxs-list <repository> (lists packages in given repository)
- [ ] nxs-get <package> (goes through all repositories available and installs package)
- [ ] nxs-del <package> (removes installed package)
- [ ] nxs-search <keyword> <opt:page> (maybe? search for a package?)
- [ ] nxs-feedback <package> (sends a message with feedback to the author of the package)
- [ ] nxs-add <repositoryurl>

**Comment by jtokarchuk** [comment]
Will need nxs to keep track of all installed packages and their versions to compare for updates.

**Comment by jtokarchuk** [comment]
possible install code (partly):

```
var arr = [ ];
var packagetofind = "nxs";

$.getJSON("https://raw.githubusercontent.com/Nextitude/nxs/master/sources.lst", function(data) {
  arr = $.map(data, function(el) { return el });
  // need to push the clientside repository listing to the array too.
  retrieveData(0)
});

function retrieveData(idx) {
	// check the first repository in array
	$.getJSON(arr[idx].url, function(data) {
      if (packagetofind in data) {
        console.log(data[packagetofind].url);
      } else {
      	idx++;
        // check to see if anything is left in the array
        retrieveData(idx);
      }
  });
}
```

**Comment by jtokarchuk** [comment]
Possible install code:

```
jQuery.get('https://raw.githubusercontent.com/AchaeaZahan/Nexus/master/Mapmod.nxs', function(data){
    console.log(data);
    try {
            var pkg = JSON.parse(data);
        } catch (e) {
            // need some sort of client text output instead.
            console.log('This does not seem to be a correct reflex package file, or it has been corrupted.');
            return;
        }
        if ((!pkg.name) || (!pkg.items) || (pkg.type !== 'group')) {
            window.alert('This does not look like a valid reflex package file.');
            return;
        }
        pkg.name = pkg.name.toLowerCase();   // in case the package was manually edited
        var pos = package_exists(pkg.name);
        if (pos <= 0) {
            client.packages.push(pkg);
        } else {
            // perhaps blurb about it existing
            client.packages[pos - 1] = pkg;
        }
        client.reflexes_fix_parents();
        window.alert('The package ' + client.ucfirst(pkg.name) + ' has been imported.');
        
        client.system_changed = true;
        client.gmcp_save_system(false);
        client.apply_settings();
        run_function("onLoad", undefined, "mapmod");
        

    });
```
